### ISSUE TITLE
To-Do list

### ISSUE THREAD

**Issue by Zephyrkul** [zephyrkul/NationCogs#1]
- [X] Lessen calls to NationStates as much as possible, namely by dropping the Founder tag for [p]nation and moving image calls to Imgur or taijitu.org
- [X] Right now, if you spam the bot commands too much, the bot will become unresponsive for up to 30 seconds. This is because the API wrapper I'm using blocks if it encounters the rate limit, hogging up the bot's resources for nothing. What do I intend to do? Rewrite the wrapper so it does not. (This is why NSApi is a separate cog now.)
- [ ] Allow multiple nation arguments for NSEndorse.
- [ ] Arrange shard arguments to specify nation/region/council after shards, to allow for better alias support.
- [X] Regional update commands, to be done after the above due to how many API requests may or may not be involved.
- [ ] [p]neb (nations endorsed by) and [p]nneb (nations not endorsed by), along with their respective count commands. As of now, I have no idea how to do these two; I hope to consult with Eluvatar if I catch him.
