### ISSUE TITLE
To-Do List (v3)

### ISSUE THREAD

**Issue by Zephyrkul** [zephyrkul/NationCogs#2]
- [ ] Create new asynchronous API wrapper.
- - [X] Create the wrapper itself.
```py
async for event, result in api("?nation=darcania", "flag", "census",
                               scale="66", mode="rank", NATION=lambda e: e):
    print(event, result)
# event is the name of the XML Element's tag
# callable / awaitable kwargs will process the specified XML Element into result
```
- - [X] Finish wrapper ratelimit; currently it ratelimits before the iteration begins, and thus before the initial request is sent, leading to potential inaccuracies. (Look into how pynationstates and others handle rate limits.)
- - [ ] Add support for [Eluvatar's](https://github.com/Eluvatar) [Trawler service](https://github.com/Eluvatar/trawler-client-python)
- - [X] Add custom user agent support
- [X] More descriptive user agent (add info about use of NationCogs by Darcania).
- [ ] Look into NS++ API, especially for use for `[p]neb` and `[p]nneb`.
- [ ] Complete #1 .
- - [ ] Allow multiple nation arguments for NSEndorse.
- - [ ] Arrange shard arguments to specify nation/region/council after shards, to allow for better alias support.
- - [ ] `[p]neb` (nations endorsed by) and `[p]nneb` (nations not endorsed by), along with their respective count commands.
